---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: README-FORESTRY.md
  label: Help
  read_only: true
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: posts
  label: Posts
  create: all
  match: "**/*"
upload_dir: ''
public_path: https://whiskybros.s3.us-east-1.amazonaws.com
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.79.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.42.1
